#!/usr/bin/cmake -P

set(repo_url https://github.com/ethereum/cable)
set(download_url ${repo_url}/raw/master)
set(cable_dir ${CMAKE_CURRENT_LIST_DIR})


function(get_modules_list OUTPUT_LIST)
    file(GLOB modules_files RELATIVE ${cable_dir} "${cable_dir}/Cable*.cmake")
    string(REPLACE ".cmake" "" modules "${modules_files}")
    set(${OUTPUT_LIST} "${modules}" PARENT_SCOPE)
endfunction()

function(download MODULE_NAME)
    set(module_file ${MODULE_NAME}.cmake)
    set(src "${download_url}/${module_file}")
    set(dst "${cable_dir}/${module_file}")
    file(DOWNLOAD "${src}" "${dst}" STATUS status)
    list(GET status 0 status_code)
    list(GET status 1 error_msg)
    if(status EQUAL 0)
        set(msg DONE)
    else()
        file(REMOVE "${dst}")
        set(msg "${status_code} ${error_msg}\n  ${src}")
    endif()
    message("Downloading ${MODULE_NAME}: ${msg}")
endfunction()

set(cmd ${CMAKE_ARGV3})
if(NOT cmd)
    set(cmd list)
endif()

if(cmd STREQUAL list)
    get_modules_list(modules)
    string(REPLACE ";" "\n  " modules "${modules}")
    message("Installed modules:\n  ${modules}")
elseif(cmd STREQUAL update)
    get_modules_list(modules)
    foreach(module ${modules})
        download(${module})
    endforeach()
elseif(cmd STREQUAL install)
    download(${CMAKE_ARGV4})
else()
    message(FATAL_ERROR "Unknown command '${cmd}'")
endif()
